const products = [
    {
        id: 1,
        name: "Minute Maid: Mango Pulpy Juice (400ml)",
        category: "Beverages",
        price: 75.00,
        rating: 4.5,
        image: "assets/images/products/min-maid-product.webp",
        promo: true,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 2,
        name: "Tushop Fresh Imported Oranges",
        category: "Fruits & Vegetables",
        price: 165.00,
        rating: 4.8,
        image: "/assets/images/products/oranges-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 3,
        name: "MacCoffee Classic (200g)",
        category: "Food Cupboard",
        price: 1350.00,
        rating: 4.7,
        image: "/assets/images/products/mac-coffee-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 4,
        name: "Blueband Original (250g)",
        category: "Food Cupboard",
        price: 148.00,
        rating: 4.3,
        image: "/assets/images/products/bband-product.png",
        promo: false,
        qty: 0,
        pamojaItem: true,
        pamojaCurrentSelected: 9,
        pamojaCurrentTotal: 30,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 5,
        name: "Brookside Whole Milk 1L Long Life",
        category: "Dairy",
        price: 156.00,
        rating: 4.8,
        image: "/assets/images/products/brookside-milk-product.webp",
        promo: true,
        qty: 0,
        pamojaItem: true,
        pamojaCurrentSelected: 16,
        pamojaCurrentTotal: 20,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 6,
        name: "Tushop Fresh Local Watermelon",
        category: "Fruits & Vegetables" || "Organic",
        price: 369.00,
        oldPrice: 369.00,
        rating: 4.6,
        image: "/assets/images/products/watermelon-product.webp",
        promo: true,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 7,
        name: "Brookside Full Cream Milk Powder Tin (500g)",
        category: "Dairy",
        price: 1198.00,
        rating: 4.6,
        image: "/assets/images/products/brookside-milk-powder-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 8,
        name: "McVities Digestive Biscuits (400g)",
        category: "Snacks",
        price: 339.00,
        rating: 4.9,
        image: "/assets/images/products/digestives-product.webp",
        promo: true,
        qty: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Mar 21'
    },
    {
        id: 9,
        name: "Tushop Fresh Mixed Size Tomatoes",
        category: "Fruits & Vegetables",
        price: 85.00,
        rating: 4.8,
        image: "/assets/images/products/tomatoes-product.webp",
        promo: true,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 10,
        name: "Mumias Sugar White (2kg)",
        category: "Food Cupboard",
        price: 278.00,
        rating: 4.7,
        image: "/assets/images/products/mumias-sugar-product.webp",
        promo: false,
        qty: 0,
        pamojaItem: true,
        pamojaCurrentSelected: 12,
        pamojaCurrentTotal: 40,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 11,
        name: "Tushop Fresh Red Onions",
        category: "Fruits & Vegetables",
        price: 98.00,
        rating: 4.9,
        image: "/assets/images/products/onions-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 12,
        name: "Rinsun 100% Sunflower Oil (3L)",
        category: "Food Cupboard",
        price: 1149.00,
        rating: 4.4,
        image: "/assets/images/products/rinsun-oil-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
    {
        id: 13,
        name: "Tushop Fresh Ripe Bananas",
        category: "Fruits & Vegetables",
        price: 250.00,
        rating: 4.9,
        image: "/assets/images/products/bananas-product.webp",
        promo: false,
        qty: 0,
        jipangeSelected: false,
        jipanges: []
    },
];

export default products;