const products = [
    {
        id: 1,
        name: "Minute Maid: Mango Pulpy Juice (400ml)",
        category: "Beverages",
        brand: "Coca Cola",
        price: 75.00,
        rating: 4.5,
        image: "assets/images/products/min-maid-product.webp",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 2,
        name: "Tushop Fresh Imported Oranges",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 165.00,
        rating: 4.8,
        image: "/assets/images/products/oranges-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 3,
        name: "MacCoffee Classic (200g)",
        category: "Food Cupboard",
        brand: 'MacCoffee',
        price: 1350.00,
        rating: 4.7,
        image: "/assets/images/products/mac-coffee-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 4,
        name: "Bio Salted Artisanal Butter (500g)",
        category: "Dairy",
        brand: 'Bio',
        price: 850.00,
        oldPrice: 879.00,
        rating: 4.7,
        image: "/assets/images/products/butter-product.png",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 5,
        name: "Blueband Original (250g)",
        category: "Food Cupboard",
        brand: "Blueband",
        price: 140.00,
        prevPrice:  148.00,
        rating: 4.3,
        image: "/assets/images/products/bband-product.png",
        promo: false,
        qty: 0,
        pamoja: true,
        pamojaCurrentSelected: 9,
        pamojaCurrentTotal: 30,
        pamojaExpiryDate: '20/04/25',
        pamojaExpiryTime: '4:30PM',
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 6,
        name: "Brookside Whole Milk 1L Long Life",
        category: "Dairy",
        brand: "Brookside",
        price: 145.00,
        prevPrice:  156.00,
        rating: 4.8,
        image: "/assets/images/products/brookside-milk-product.webp",
        promo: true,
        qty: 0,
        pamoja: true,
        pamojaCurrentSelected: 16,
        pamojaCurrentTotal: 20,
        pamojaExpiryDate: '20/04/25',
        pamojaExpiryTime: '5:00PM',
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 7,
        name: "Mlango Farms Organic Curly Kale",
        category: "Fruits & Vegetables",
        brand: 'Mlango Farms',
        price: 35.00,
        rating: 4.85,
        image: "/assets/images/products/kale-product.png",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 8,
        name: "Tushop Fresh Local Watermelon",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 320.00,
        oldPrice: 369.00,
        rating: 4.6,
        image: "/assets/images/products/watermelon-product.webp",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 9,
        name: "TuShop Fresh Mwea Pishori Rice (1kg)",
        category: "Food Cupboard",
        brand: 'TuShop Fresh',
        price: 190.00,
        oldPrice: 205.00,
        rating: 4.6,
        image: "/assets/images/products/rice-product.png",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 10,
        name: "Brookside Full Cream Milk Powder Tin (500g)",
        category: "Dairy",
        brand: "Brookside",
        price: 1198.00,
        rating: 4.6,
        image: "/assets/images/products/brookside-milk-powder-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 11,
        name: "Mlango Farms Organic Red Chard",
        category: "Fruits & Vegetables",
        brand: 'Mlango Farms',
        price: 55.00,
        rating: 4.9,
        image: "/assets/images/products/red-chard-spinach-product.png",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 12,
        name: "McVities Digestive Biscuits (400g)",
        category: "Snacks",
        brand: 'McVites',
        price: 339.00,
        rating: 4.9,
        image: "/assets/images/products/digestives-product.webp",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 13,
        name: "Tushop Fresh Mixed Size Tomatoes",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 85.00,
        rating: 4.8,
        image: "/assets/images/products/tomatoes-product.webp",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 14,
        name: "Rascals 17kgs Premium CoComelon Training Diaper Pants - Size 7 (22pcs)",
        category: "Baby Care",
        brand: 'Rascals',
        price: 1999.00,
        rating: 4.8,
        image: "/assets/images/products/diapers-product.png",
        promo: true,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 15,
        name: "Mumias Sugar White (2kg)",
        category: "Food Cupboard",
        brand: 'Mumias',
        price: 270.00,
        prevPrice:  278.00,
        rating: 4.7,
        image: "/assets/images/products/mumias-sugar-product.webp",
        promo: false,
        qty: 0,
        pamoja: true,
        pamojaCurrentSelected: 12,
        pamojaCurrentTotal: 40,
        pamojaExpiryDate: '20/04/25',
        pamojaExpiryTime: '3:00PM',
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 16,
        name: "Tushop Fresh Fresh Red Cabbage",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 152.00,
        rating: 4.7,
        image: "/assets/images/products/red-cabbage-product.png",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 17,
        name: "Tushop Fresh Red Onions",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 98.00,
        rating: 4.9,
        image: "/assets/images/products/onions-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 18,
        name: "Rinsun 100% Sunflower Oil (3L)",
        category: "Food Cupboard",
        brand: 'Rinsun',
        price: 1149.00,
        rating: 4.4,
        image: "/assets/images/products/rinsun-oil-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 19,
        name: "VP Foods Baby Plum Tomatoes",
        category: "Fruits & Vegetables",
        brand: 'VP Foods',
        price: 59.00,
        rating: 4.7,
        image: "/assets/images/products/baby-plum-tomatos-product.png",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 20,
        name: "Tushop Fresh Ripe Bananas",
        category: "Fruits & Vegetables",
        brand: 'TuShop Fresh',
        price: 250.00,
        rating: 4.9,
        image: "/assets/images/products/bananas-product.webp",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 21,
        name: "TuShop Fresh Mixed Sizes Eggs",
        category: "Dairy",
        brand: 'TuShop Fresh',
        price: 205.00,
        oldPrice: 250.00,
        rating: 4.9,
        image: "/assets/images/products/eggs-product.png",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
    {
        id: 22,
        name: "Kenchic Spring Chicken (750g)",
        category: "Meat",
        brand: 'Kenchic',
        price: 560.00,
        oldPrice: 560.00,
        rating: 4.9,
        image: "/assets/images/products/chicken-product.png",
        promo: false,
        qty: 0,
        pamoja: false,
        pamojaCurrentSelected: 0,
        pamojaCurrentTotal: 0,
        jipangeSelected: false,
        jipanges: [],
        jipangeDate: 'Apr 21'
    },
];

export default products;